services:
  network-deploy-service:
    networks:
      - post-application

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8083/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8070/eureka/

  microservice-rabbitmq-config:
    extends:
      service: microservice-eureka-config
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq