services:
  configserver:
    image: "sametyildiz/configserver:1.0.0"
    container_name: configserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eureka:
    image: "sametyildiz/eurekaserver:1.0.0"
    container_name: eureka
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  gateway:
    image: "sametyildiz/gatewayserver:1.0.0"
    container_name: gateway
    ports:
      - "8072:8072"
    depends_on:
      user:
        condition: service_healthy
      post:
        condition: service_healthy
      comment:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  user:
    image: "sametyildiz/user:1.0.0"
    container_name: user-ms
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "user"
    extends:
      file: common-config.yml
      service: microservice-rabbitmq-config

  post:
    image: "sametyildiz/post:1.0.0"
    container_name: post-ms
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "post"
    extends:
      file: common-config.yml
      service: microservice-rabbitmq-config

  comment:
    image: "sametyildiz/comment:1.0.0"
    container_name: comment-ms
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "comment"
    extends:
      file: common-config.yml
      service: microservice-rabbitmq-config

  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  post-application:
    driver: "bridge"